import type { AgentKind, ItemStatus, ItemType, Role, SessionState } from "./types";

export const STATUS_LABEL: Record<ItemStatus, string> = {
  draft: "Draft",
  ready: "Ready",
  in_progress: "In progress",
  blocked: "Blocked",
  in_review: "In review",
  awaiting_approval: "Awaiting approval",
  done: "Done",
  cancelled: "Cancelled",
};

export const TYPE_LABEL: Record<ItemType, string> = { epic: "Epic", story: "Story", task: "Task", bug: "Bug", spike: "Spike" };
export const TYPE_PLURAL: Record<ItemType, string> = { epic: "Epics", story: "Stories", task: "Tasks", bug: "Bugs", spike: "Spikes" };

export const ROLE_LABEL: Record<Role | "advisor", string> = {
  orchestrator: "Orchestrator",
  advisor: "Advisor",
  coder: "Coder",
  reviewer: "Reviewer",
  ui_reviewer: "UI reviewer",
  researcher: "Researcher",
  debugger: "Debugger",
  mechanical: "Mechanical",
};

export const AGENT_LABEL: Record<AgentKind, string> = { claude: "Claude", codex: "Codex", agy: "agy", cursor: "Cursor", fake: "Fake" };
// README §19 troubleshooting: how each agent signs in.
export const AGENT_LOGIN_CMD: Record<AgentKind, string> = {
  claude: "claude", codex: "codex login", agy: "agy", cursor: "cursor-agent login", fake: "true",
};

export const SESSION_LABEL: Record<SessionState | "queued" | "waiting" | "stale" | "preflight_failed", string> = {
  spawning: "Starting",
  running: "Running",
  pause_requested: "Pause requested",
  quiescing: "Finishing current step",
  stopping: "Stopping",
  paused: "Paused",
  interrupted: "Interrupted",
  completed: "Completed",
  failed: "Failed",
  crashed: "Crashed",
  cancelled: "Cancelled",
  queued: "Queued",
  waiting: "Waiting",
  stale: "No activity for 30 min",
  preflight_failed: "Failed",
};

export const C = {
  appTitle: "Agent Swarm",
  needsYou: "Needs you",
  newSpike: "New spike",
  newItem: "New item",
  search: "Search name or key…",
  type: "Type",
  status: "Status",
  all: "All",
  clearFilters: "Clear filters",
  hierarchy: "Hierarchy",
  kanban: "Kanban",
  dependencies: "Dependencies",
  cardLevel: "Card level",
  tasks: "Tasks",
  stories: "Stories",
  topLevel: "Top-level items",
  groupBy: "Group by",
  groupRoot: "Top-level item",
  flat: "Flat",
  moveTo: "Move to…",
  updating: "Updating…",
  scope: "Scope",
  root: "Root",
  neighbourhood: "Neighbourhood",
  expandHop: "Expand one hop",
  fit: "Fit",
  reset: "Reset",
  find: "Find…",
  depLegend: "A → B: B waits for A",
  openRoot: "Open root",
  overview: "Overview",
  checkpoints: "Checkpoints",
  brief: "Brief",
  acceptance: "Acceptance",
  blockedBy: "Blocked by",
  blocks: "Blocks",
  addDependency: "Add dependency",
  artifacts: "Artifacts",
  startOrchestrator: "Start orchestrator",
  queueOrchestrator: "Queue orchestrator",
  viewOrchestrator: "View orchestrator",
  terminal: "Terminal",
  openTerminal: "Open terminal",
  openOrchestratorTerminal: "Open orchestrator terminal",
  orchestratorPaused: "Orchestrator is paused. Resume it to continue.",
  orchestratorNotRunning: "Orchestrator isn't running.",
  optionsOffered: "Options offered",
  writtenBySwarm: "Written by Swarm",
  approveSection: "Approve section",
  approvePlan: "Approve plan",
  approveReport: "Approve report",
  acceptEpic: "Accept epic",
  acceptFix: "Accept fix",
  closeSpike: "Close spike",
  closeSpikeRow: "Close spike?",
  requestChanges: "Request changes",
  sendChangeRequest: "Send change request",
  viewFullSpec: "View full spec",
  view: "View",
  showInHierarchy: "Show in hierarchy",
  createItem: "Create item",
  addStory: "Add story",
  addTask: "Add task",
  back: "← Back",
  cancel: "Cancel",
  tryAgain: "Try again",
  review: "Review",
  answer: "Answer",
  prompt: "Prompt",
  blocker: "Blocker",
  comment: "Comment",
  pause: "Pause",
  pauseGroup: "Pause group",
  pausing: "Pausing…",
  resume: "Resume",
  resuming: "Resuming…",
  acknowledge: "Acknowledge",
  retry: "Retry",
  agents: "Agents",
  priority: "Priority",
  advisor: "Advisor",
  noAdvisor: "No advisor",
  defaultClaudeCode: "Default (Claude Code)",
  notSupported: "Not supported",
  defaultsFromSettings: "Defaults from Settings",
  workerRoles: "Worker Roles",
  customizeWorkerRoles: "Customize worker roles for this orchestrator",
  name: "Name",
  title: "Title",
  parent: "Parent",
  intent: "Intent",
  featureSpike: "Feature spike",
  debugSpike: "Debug spike",
  featureCaption: "Creates a spike to explore this request and turn it into an epic.",
  debugCaption: "Creates a spike to find the root cause and turn it into a bug with a fix plan.",
  repositories: "Repositories",
  repositoriesOptional: "Repositories (optional)",
  reposCaption: "The spike suggests repositories and asks you to confirm them.",
  searchRepos: "Search repos…",
  recent: "Recent",
  addFolder: "Add folder…",
  rescan: "Rescan",
  agent: "Agent",
  model: "Model",
  effort: "Effort",
  requestOptional: "Request (optional)",
  confirmRepositories: "Confirm repositories",
  proposed: "Proposed",
  suggestedAdditions: "Suggested additions",
  addAnother: "Add another",
  youSelected: "You selected",
  commentOptional: "Comment (optional)",
  questions: "Questions",
  approvals: "Approvals",
  reviews: "Reviews",
  noChangeNeeded: "No change needed",
  viewSpike: "View spike",
  viewItem: "View item",
  showTopLevel: "Show top-level items",
  context: "context",
  storiesCaption: "Stories within epics",
  unassignedLane: "Unassigned · Parent missing",
  // §17.3
  nameEmpty: "Enter a name containing a letter or number.",
  nameTaken: "This agent name is already in use.",
  chooseRepo: "Choose at least one repository.",
  scanning: "Scanning your home folder…",
  repoMissing: "Repository is unavailable. Choose another location.",
  repoDirty: "Has uncommitted changes. The orchestrator works in its own worktree.",
  notARepo: "No git repository found in this folder.",
  modelUnavailable: "Choose a model available for this agent.",
  chooseAgent: "Choose an agent.",
  neverScanned: "Never scanned",
  neverFetched: "Never fetched",
  launchFailure: "Couldn't start orchestrator. Your entries are saved.",
  queuedCaption: "Starts when an agent slot becomes available.",
  orchestratorExists: "This item already has an orchestrator.",
  epicDone: "Accept this epic to mark it Done.",
  bugDone: "Accept this fix to mark it Done.",
  spikeDone: "This spike reaches Done after materialization.",
  awaitingNonSpike: "Only spikes can await approval.",
  cycle: "This dependency would create a cycle.",
  depHierarchy: "A task can't depend on its own story or epic.",
  spikeViaNewItem: "Spikes start with an intent. Use New spike.",
  staleRevision: "This item changed elsewhere. Showing its latest status.",
  staleApproval: "This request changed. Review the latest version.",
  emptyChange: "Add a comment describing what to change.",
  daemonDown: "Connection lost. Status changes are unavailable.",
  // §17.4
  noItems: "No work items yet.",
  filteredNone: "No items match these filters.",
  kanbanNoTasks: "No tasks yet. Open Hierarchy to add or inspect work.",
  kanbanNoStories: "No stories match. Stories belong to epics.",
  kanbanFiltered: "No tasks match these filters.",
  emptyColumn: "No items",
  noDeps: "No dependencies for this item.",
  noCheckpoints: "No checkpoints yet.",
  resolved: "Already resolved.",
  outsideView: "This item is outside the current view.",
  inboxEmpty: "Nothing needs your attention.",
  hiddenByFilters: "Hidden by the current filters.", // ruling F11, with clearFilters
} as const;

const joinParts = (parts: string[]) => parts.filter((p) => p !== "").join(" · ");

export const T = {
  matches: (n: number) => `${n} matches`,
  startedFrom: (key: string) => `Started from ${key}`,
  agentName: (kebab: string) => `Agent name: ${kebab}`,
  selected: (names: string) => `Selected: ${names}`,
  scannedAgo: (age: string) => `Scanned ${age} ago`,
  defaultLevel: (level: string) => `Default (${level})`,
  storyDoneDenied: (key: string) => `Couldn't move ${key} to Done. Complete all child tasks and their checkpoints first.`,
  taskDoneDenied: (key: string) => `Couldn't move ${key} to Done. No agent has reported it complete.`,
  genericStatus: (status: string) => `Couldn't update status. The item remains ${status}.`,
  agentNotInstalled: (agent: string) => `${agent} isn't installed on this Mac.`,
  agentNotSignedIn: (agent: string, cmd: string) => `${agent} isn't signed in. Run \`${cmd}\` in a terminal.`,
  superpowersMissing: (agent: string) => `Install the superpowers plugin for ${agent} to run orchestrators.`,
  catalogStale: (age: string, error: string) => `Model list from ${age} ago. Couldn't refresh: ${error}`,
  catalogNeverFetched: (error: string) => `Never fetched. Couldn't refresh: ${error}`,
  modelGone: (model: string, agent: string) => `${model} is no longer offered by ${agent}.`,
  effortUnavailable: (level: string, model: string) => `${level} isn't available for ${model}; using the default.`,
  cancelOrchestrator: (name: string, n: number) => `Cancel ${name} and its ${n} agents?`,
  finished: (n: number) => `Finished (${n})`,
  colHeader: (label: string, n: number) => `${label} · ${n}`,
  colTooltip: (shown: number, total: number) => `${shown} of ${total} items`,
  agentsTooltip: (n: number) => `${n} agents working in this item and its children.`,
  typeHint: (typePlural: string) => `${typePlural} have no task cards yet. Switch Card level to Top-level items to see them.`,
  laneFinished: (n: number, done: number, cancelled: number, unit: string) =>
    `All ${n} ${unit} finished · ${done} done, ${cancelled} cancelled.`,
  laneDone: (n: number, unit: string) => `All ${n} ${unit} done.`,
  progress: (done: number, total: number, unit: string) => `${done} of ${total} ${unit} done`,
  blockedBy: (first: string, extra: number) => `Blocked by ${first}${extra > 0 ? ` +${extra}` : ""}`,
  needs: (n: number) => `Needs ${n}`,
  needsYouButton: (n: number) => `Needs you ${n}`,
  laneHeader: (n: number, unit: string, needYou: number, blocked: number) =>
    joinParts([`${n} ${unit}`, needYou > 0 ? `${needYou} need you` : "", blocked > 0 ? `${blocked} blocked` : ""]),
  confirmNRepos: (n: number) => `Confirm ${n} repositories`,
  approveSectionRow: (title: string) => `Approve "${title}"`,
  duplicateOf: (key: string) => `Duplicate of ${key}`,
  reason: (r: string) => `Reason: ${r}`,
  requestedBy: (name: string, age: string) => `Requested by ${name} · ${age}`,
  proposedBy: (name: string, age: string) => `Proposed by ${name} · ${age}`,
  advice: (advisor: string, duration: string, tokens: string, cost: string) =>
    joinParts(["Advice", advisor, duration, tokens, cost]),
  advisorTotals: (tokens: string, cost: string) => joinParts(["Advisor", `${tokens} tokens`, cost]),
};
